api/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from .views import StatusView


app_name = 'api'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^status$', StatusView.as_view(), name='status'),
]

fbxnano/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fbxnano.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^events$', TemplateView.as_view(template_name='events.html'), name='events'),
    url(r'^links$', TemplateView.as_view(template_name='links.html'), name='links'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^alerts/', include('alerts.urls', namespace='alerts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^auth/', include('prosodyauth.urls', namespace='auth')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^policies/', include('policies.urls', namespace='policies')),
)

tools/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView


from . import views

app_name = 'tools'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    path('stories/', views.StoryListView.as_view(), name='story_list'),
    path('stories/<int:pk>/', views.StoryDetailView.as_view(), name='story_detail'),

    path('stories/<int:story_id>/characters/<int:pk>', views.CharacterDetailView.as_view(), name='character_detail'),
    path('stories/<int:story_id>/characters/<int:pk>/edit', views.CharacterEditView.as_view(), name='character_edit'),
    path('stories/<int:story_id>/characters/<int:pk>/notes', views.CharacterNotesView.as_view(), name='character_notes'),
    path('stories/<int:story_id>/characters/new', views.CharacterCreateView.as_view(), name='character_create'),

    re_path(r'^characters(?:/.*)?$', RedirectView.as_view(pattern_name='tools:story_list')),
]

xmpp_dev/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xmpp_dev.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^auth/', include('prosodyauth.urls')),
)

tools/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import Truncator


# Create your models here.
class Story(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=127)

    def get_absolute_url(self):
        return reverse('tools:story_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '"{}" by {}'.format(self.title, self.owner)

class Character(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    age = models.SmallIntegerField(null=True, blank=True)
    appearance = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('tools:character_detail', kwargs={'story_id': self.story_id, 'pk': self.pk})

    def __str__(self):
        return '{} from {}'.format(self.name, self.story)


class QuestionBase(models.Model):
    question = models.TextField()
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True

    def __str__(self):
        q = Truncator(self.question).words(5)
        return q


class CharacterNotes(QuestionBase):
    pass


class AnswerBase(models.Model):
    answer = models.TextField()

    class Meta:
        abstract = True

    def __str__(self):
        a = Truncator(self.answer).words(5)
        return a


class CharacterNotesAnswer(AnswerBase):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    question = models.ForeignKey(CharacterNotes, on_delete=models.CASCADE)

tools/views/_mixins.py
from django.forms import ModelChoiceField


from tools.models import Character,CharacterNotes


class OwnedItemsMixin:
    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class CharacterFormMixin(object):
    model = Character
    fields = ['owner','name','age','appearance','story',]
    context_object_name = 'character'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        try:
            # This convoluted-seeming logic is necessary because the data is in
            # an immutable QueryDict instance, rather than a simple dict
            data = kwargs['data'].copy() # make a copy, which is mutable
            data['owner'] = self.request.user.id # update owner to current user
            kwargs['data'] = data # replace original data with our updated copy
        except KeyError:
            pass

        return kwargs

    def get_form_class(self):
        form = super().get_form_class()

        class StoryChoiceField(ModelChoiceField):
            def label_from_instance(self, obj):
                return obj.title

        stories = self.request.user.story_set
        form.base_fields['story'] = StoryChoiceField(queryset=stories)

        return form

    def get_context_data(self):
        context = super().get_context_data()
        context['notes'] = CharacterNotes.objects.filter(is_active=True)

        return context

tools/views/character.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,redirect
from django.views.generic import ListView,View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView


from tools.models import Character,CharacterNotes,CharacterNotesAnswer,Story
from ._mixins import CharacterFormMixin,OwnedItemsMixin


# Create your views here.

class CharacterCreateView(CharacterFormMixin, LoginRequiredMixin, CreateView):
    pass


class CharacterEditView(CharacterFormMixin, OwnedItemsMixin, LoginRequiredMixin, UpdateView):
    pass


class CharacterDetailView(LoginRequiredMixin, OwnedItemsMixin, DetailView):
    model = Character
    context_object_name = 'character'


class CharacterNotesView(LoginRequiredMixin, View):
    def post(self, request, story_id, pk):
        character = Character.objects.get(owner=request.user, pk=pk)

        for field in request.POST:
            if not field.startswith('note-'):
                continue

            text = request.POST[field]

            note_id = field.split('-')[1]
            question = CharacterNotes.objects.get(pk=field.split('-')[1])

            if text:
                answer, created = CharacterNotesAnswer.objects.get_or_create(character=character, question=question)
                answer.answer = text
                answer.save()
            else:
                CharacterNotesAnswer.objects.filter(
                        character=character,
                        question=question).delete()

        return redirect(character)

tools/views/story.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,redirect
from django.views.generic import ListView,View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView


from tools.models import Character,CharacterNotes,CharacterNotesAnswer,Story
from ._mixins import OwnedItemsMixin


# Create your views here.

class StoryListView(LoginRequiredMixin, OwnedItemsMixin, ListView):
    model = Story
    context_object_name = 'stories'

    def get_queryset(self):
        q = super().get_queryset()
        return q.order_by('title')


class StoryDetailView(LoginRequiredMixin, OwnedItemsMixin, DetailView):
    model = Story
    context_object_name = 'story'

tools/templates/tools/character_detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load frontend_extras %}

{% block header %}
{{ character.name }}
<div class="tools-controls">
	<a class="btn btn-default btn-sm" href="{% url 'tools:character_edit' story_id=character.story_id pk=character.id %}">Edit</a>
	<a class="btn btn-default btn-sm" href="{% url 'tools:story_detail' pk=character.story_id %}">Back</a>
</div>
{% endblock header %}

{% block content %}
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Basic Info</h3>
	</div>
	<div class="panel-body">
		<div>
			<strong>Age:</strong> {{ character.age|default:'-' }}
		</div>
		<div>
			<strong>Appearance:</strong> {{ character.appearance|default:'-' }}
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Worksheet</h3>
	</div>
	<div class="panel-body">
		<div class="character-notes">
			{% for notes in character.characternotesanswer_set.all %}
			<div class="character-note">
				<div class="character-note-question">
					{{ notes.question.question }}
				</div>
				<div class="character-note-answer">
					{{ notes.answer }}
				</div>
			</div>
			{% empty %}
			<em>Edit your character to learn more about him/her!</em>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock content %}

tools/templates/tools/character_form.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load form_extras %}
{% load tools_extras %}

{% block header %}
Create Character
{% endblock header %}

{% block content %}
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Basic Info</h3>
	</div>
	<div class="panel-body">
		{% if form.non_field_errors %}
		<div class="alert alert-danger">{{ form.non_field_errors }}</div>
		{% endif %}
		<form action="" method="post" class="form-label-col-2">
			{% csrf_token %}
			{% bs_field form.name %}
			{{ form.name.errors }}
			{% bs_field form.age %}
			{{ form.age.errors }}
			{% bs_field form.appearance %}
			{{ form.appearance.errors }}
			{% bs_field form.story %}
			{{ form.story.errors }}
			<button class="btn btn-success" type="submit">Save</button>
			{% if character.id %}
			<a class="btn btn-default" href="{{ character.get_absolute_url }}">
				{% else %}
				<a class="btn btn-default" href="{% url 'tools:character_list' %}">
					{% endif %}
					Cancel
				</a>
			</form>
		</div>
	</div>
{% if character.id %}
<span class="text-danger">
	Basic Info and Worksheet must be saved separately.
	Saving one will discard changes made to the other!
</span>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Worksheet</h3>
	</div>
	<div class="panel-body">
		<form action="{% url 'tools:character_notes' story_id=character.story_id pk=character.id %}" method="post">
			<button class="btn btn-success" type="submit">Save</button>
			<a
				class="btn btn-default"
				href="{% if character.id %}{{ character.get_absolute_url }}{% else %}{% url 'tools:character_list' %}{% endif %}">
				Cancel
			</a>
			{% csrf_token %}
			<div class="character-notes">
				{% for note in notes %}
				<div class="character-note">
					<div class="character-note-question">
						{{ note.question }}
					</div>
					<div class="character-note-answer">
						<textarea
							class="form-control"
							name="note-{{ note.id }}-answer"
							id="note-{{ note.id }}-answer">{% note_response note character %}</textarea>
					</div>
				</div>
				{% endfor %}
			</div>
			<button class="btn btn-success" type="submit">Save</button>
			<a
				class="btn btn-default"
				href="{% if character.id %}{{ character.get_absolute_url }}{% else %}{% url 'tools:character_list' %}{% endif %}">
				Cancel
			</a>
		</form>
	</div>
</div>
{% endif %}
{% endblock content %}

tools/templates/tools/character_list.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load frontend_extras %}

{% block header %}
Your Characters
{% endblock header %}

{% block content %}
<ul>
	{% for character in characters %}
	<li><a href="{% url 'tools:character_detail' pk=character.id %}">{{ character.name }}</a></li>
	{% endfor %}
</ul>
<a class="btn btn-default btn-sm" href="{% url 'tools:character_create' %}">New Character</a>
{% endblock content %}

tools/templates/tools/story_detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load frontend_extras %}

{% block header %}
{{ story.title }}
<div class="tools-controls">
	<a class="btn btn-default btn-sm" href="">Edit</a>
	<a class="btn btn-default btn-sm" href="{% url 'tools:story_list' %}">Back</a>
</div>
{% endblock header %}

{% block content %}
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">{{ story.title }}</h3>
	</div>
	<div class="panel-body">
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Characters</h3>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>Name</th>
						<th>Age</th>
						<th>Description</th>
					</tr>
				</thead>
				<tbody>
					{% for character in story.character_set.all %}
					<tr>
						<td><a href="{{ character.get_absolute_url }}">{{ character.name }}</a></td>
						<td>{{ character.age | default_if_none:'-'}}</td>
						<td>{{ character.appearance | default:'-' }}</td>
					</tr>
					{% empty %}
					<tr>
						<td colspan="3">
							<em>You haven't added any characters yet!</em>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock content %}

tools/templates/tools/story_list.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load frontend_extras %}

{% block header %}
Your Stories
{% endblock header %}

{% block content %}
<div class="table-responsive">
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>Title</th>
				<th>Genre</th>
				<th>Synopsis</th>
			</tr>
		</thead>
		<tbody>
			{% for story in stories %}
			<tr>
				<td><a href="{{ story.get_absolute_url }}">{{ story.title }}</a></td>
				<td>Sci-Fi</td>
				<td>A story about…</td>
			</tr>
			{% empty %}
			<tr>
				<td colspan="3">
					<em>You haven't created any stories yet!</em>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<a class="btn btn-default btn-sm" href="">New Story</a>
{% endblock content %}