api/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from .views import StatusView


app_name = 'api'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^status$', StatusView.as_view(), name='status'),
]

chat/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView


from . import views

app_name = 'chat'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    path('', TemplateView.as_view(template_name='chat/index.html'), name='index'),
    path('nabu', login_required(views.NabuView.as_view()), name='nabu'),
    #url(r'^candy$', login_required(views.CandyView.as_view()), name='candy'),
]

contact/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'contact'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.contact, name='contact'),
]

fbxnano/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fbxnano.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^events$', TemplateView.as_view(template_name='events.html'), name='events'),
    url(r'^links$', TemplateView.as_view(template_name='links.html'), name='links'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^alerts/', include('alerts.urls', namespace='alerts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^auth/', include('prosodyauth.urls', namespace='auth')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^policies/', include('policies.urls', namespace='policies')),
)

passwordless/urls.py
from django.conf.urls import include, url
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'auth'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login', views.LoginView.as_view(), name='login'),
    url(r'^logout', views.LogoutView.as_view(), name='logout'),
    url(r'^register', views.RegisterView.as_view(), name='register'),
    url(r'^n/(?P<token>[0-9a-zA-Z]+)$', views.AuthnView.as_view(), name='authn'),
    url(r'^api/json$', csrf_exempt(views.ApiAuthView.as_view()), name='api_json'),
    url(r'^apppasswords$', views.AppPasswordListView.as_view(), name='apppasswords'),
    url(r'^apppasswords/revoke$', views.AppPasswordRevokeView.as_view(), name='revoke_apppassword'),
    url(r'^apppasswords/create$', views.AppPasswordCreateView.as_view(), name='create_apppassword'),
]

prosodyauth/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login', views.login, name='login'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^register', views.register, name='register'),
    url(r'^resend', views.resend, name='resend'),
    url(r'^activate/(?P<token>[0-9a-zA-Z]+)', views.activate, name='activate'),
]

xmpp_dev/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xmpp_dev.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^auth/', include('prosodyauth.urls')),
)

chat/views.py
from datetime import datetime, timedelta
import jwt
import os


from django.shortcuts import render
from django.conf import settings
from django.views.generic.base import TemplateView


key = os.path.join(
    os.path.dirname(__file__),
    'ecc',
    'key.pem',
)
with open(key, 'r') as fh:
    ecc_private = fh.read()


# Create your views here.
class NabuView(TemplateView):
    template_name = 'chat/nabu.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        data = {
            'sub': self.request.user.username,
            'iss': settings.NABU['jwt']['iss'],
            'aud': settings.NABU['jwt']['aud'],
            'exp': datetime.utcnow() + timedelta(**settings.NABU['jwt']['exp']),
        }
        token = jwt.encode(data, ecc_private, algorithm='ES256')
        context['token'] = token.decode('utf-8')

        context['nabu_server'] = settings.NABU['server']

        return context

chat/templates/chat/adium.html
{% load static from staticfiles %}
{% load chat_extras %}
<p>
<a href="https://adium.im/" target="_blank">Adium</a> is our recommended chat
client for Mac users.
</p>

<h3>Setting up Adium</h3>
<p>
Once you have <a href="https://adium.im/" target="_blank">downloaded</a>
and installed Adium, add a new account by opening the File menu, going to the
Add Account sub-menu, and choosing {% jabber_proto %} (Jabber).
</p>
<div class="pull-right">
	<img src="{% static 'chat/img/adium_setup.png' %}" alt="Setup Adium" class="img-responsive" />
</div>
<p>
To configure your account, set your options as so:
<ol>
	<li>Jabber ID: <span class="text-danger">{{ user.jid_node|default:"<em>Your username</em>" }}</span>@{% jabber_domain %}</li>
	<li>Password: <em class="text-danger">The <a class="text-danger" href="{% url 'auth:apppasswords' %}">App Password</a> you generated.</em></li>
</ol>
</p>
<p>
Under Personal, give yourself an alias; this only shows up to you, and
identifies your own messages. I like to set it to "Me".
</p>
<p>
Now click the OK button to finish and connect to the server.
</p>
{% include 'chat/annika-intro.html' %}

chat/templates/chat/annika-intro.html
<div class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Joining the Chatroom</h3>
	</div>
	<div class="panel-body">
		<p>
		When you log in for the first time,
		<a href="#annika" data-toggle="collapse" aria-expanded="false" aria-controls="annika" data-parent="#accordion">Annika</a>
		will ask you to be her friend. She's here to be helpful, and can make
		joining the group chat a lot easier. After you accept her request, you
		can say "<strong class="text-primary">invite me</strong>" to her, and
		she'll send you an invitation to join the group chat room.
		</p>
	</div>
</div>

chat/templates/chat/annika.html
<p>
Annika is our friendly local chat bot.
</p>

<h3>Sending Annika Commands</h3>
<p>
There are two ways to send commands to Annika:
<ul>
	<li>In a single-user chat, simply say the command (e.g. "plot bunny")</li>
	<li>In a group chat, start with her name (e.g. "annika, plot bunny")</li>
</ul>
When interacting with her in a group chat, she will also respond to the nickname
"Annie", e.g. "annie, plot bunny".
</p>

<h3>Useful Commands</h3>
<p>
Here is a quick rundown of some of her more useful commands to help you in
reaching 50,000 words:
</p>
<dl class="dl-horizontal">
	<dt>arcanobabble</dt><dd>Random arcanobabble</dd>
	<dt>divination</dt><dd>Get a random kind of divination (e.g. chiropteromancy)</dd>
	<dt>diviner</dt><dd>Get a random kind of diviner (e.g. chiropteromancer)</dd>
	<dt class="text-primary">invite me</dt><dd class="text-primary">Annika will invite you the Nano group chat room (non-Web Chat users)</dd>
	<dt>plot bunny</dt><dd>Get a random plot bunny</dd>
	<dt>plot ninja</dt><dd>Get a random plot ninja</dd>
	<dt>random name</dt><dd>Get a random name</dd>
	<dt>random job</dt><dd>Alias of "random profession"</dd>
	<dt>random profession</dt><dd>Get a random profession</dd>
	<dt>technobabble</dt><dd>Random technobabble generator</dd>
</dl>
<p>
You can also specify a name when asking for a plot bunny (e.g. "annika, plot
bunny bob") to have that name inserted into her response (e.g. "Bob is out
driving when the car stops running."). Also, when asking for a random name,
Annika is pretty good at figuring out if you're asking for a male or female
name: "random name male", "random male name", "random name man", "random man
name" &mdash; these examples would all provide a man's name in her response.
You can of course leave out the gender to get a randomly picked name of either.
</p>

chat/templates/chat/general.html
{% load static from staticfiles %}
{% load chat_extras %}
{% load frontend_extras %}
{% if user.is_authenticated %}
<p>
	<button type="button" class="btn btn-primary" data-popup-uri="{% url 'chat:nabu' %}">{% octicon 'comment-discussion' %} Launch Web Chat</button>
	<span class="text-info">(Opens in a new window.)</span>
</p>
{% else %}
<p>
To chat directly in your browser, you will first need to
<a href="{% url 'auth:login' %}">log into the site</a>.
</p>
{% endif %}
<p>
This year AKWriters is launching a new chat application. There may be some rough
edges still, so if you encounter any issues let Kromey know in the chat, on
<a target="_blank" href="https://nanowrimo.org/participants/kromey">NaNoWriMo's website</a>,
or in the
<a target="_blank" href="https://fairbanksnano.org">Fairbanks Nano Facebook group</a>.
You can also use the <a href="{% url 'contact:contact' %}">Contact Us</a> page on this site.
</p>

chat/templates/chat/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load chat_extras %}
{% load frontend_extras %}

{% block header %}
AKWriters Chat
{% endblock header %}

{% block content %}
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="heading-welcome" data-toggle="collapse" data-parent="#accordion" data-target="#welcome" aria-expanded="false" aria-controls="welcome">
			<h4 class="panel-title">
				Welcome
			</h4>
		</div>
		<div id="welcome" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-welcome">
			<div class="panel-body">
				{% include 'chat/general.html' %}
			</div>
		</div>
	</div>
	{% comment %}
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="heading-pidgin" data-toggle="collapse" data-parent="#accordion" data-target="#pidgin" aria-expanded="false" aria-controls="pidgin">
			<h4 class="panel-title">
				Windows/Linux: Pidgin
			</h4>
		</div>
		<div id="pidgin" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-pidgin">
			<div class="panel-body">
				{% include 'chat/pidgin.html' %}
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="heading-adium" data-toggle="collapse" data-parent="#accordion" data-target="#adium" aria-expanded="false" aria-controls="adium">
			<h4 class="panel-title">
				Mac: Adium
			</h4>
		</div>
		<div id="adium" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-adium">
			<div class="panel-body">
				{% include 'chat/adium.html' %}
			</div>
		</div>
	</div>
	{% endcomment %}
	{% comment %}
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="heading-annika" data-toggle="collapse" data-parent="#accordion" data-target="#annika" aria-expanded="false" aria-controls="annika">
			<h4 class="panel-title">
				{% octicon 'hubot' %} Annika &mdash; Our Chat Bot
			</h4>
		</div>
		<div id="annika" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-annika">
			<div class="panel-body">
				{% include 'chat/annika.html' %}
			</div>
		</div>
	</div>
	{% endcomment %}
</div>
{% endblock content %}

chat/templates/chat/nabu.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Nabu</title>
		{% load static from staticfiles %}
		<link rel="stylesheet" href="{% static 'nabu/nabu.css' %}">
		<script src="{% static 'nabu/vue.js' %}"></script>
	</head>
	<body>
		<div id="nabu" data-jwt="{{ token }}" data-server="{{ nabu_server }}">
			{% verbatim nabu %}
			<nav class="navbar">
				<h1>AKWriters Chat</h1>
				<slide-toggle v-if="allow_notifications" v-model="show_notifications">Notifications</slide-toggle>
			</nav>

			<div v-cloak v-if="status_msg !== null" id="login">
				<h2>{{ status_msg }}</h2>
			</div>
			<template v-cloak v-else>
				<div id="room-container">
					<div id="message-box">
						<template v-for="m in messages">
							<div v-if="m.type == 'join'" class="system">
								{{ m.from }} has joined the room
							</div>
							<div v-else-if="m.type == 'leave'" class="system">
								{{ m.from }} has left the room
							</div>
							<div v-else-if="m.type == 'unread'" class="unread"></div>
							<div v-else :class="[m.type, m.from==username?'self':'']" :style="roster_colors[m.from]">
								<div class="from" v-if="m.from">{{ m.from }}</div>
								<img class="img" v-if="m.img_src" :src="m.img_src">
								<div class="body" v-html="m.body"></div>
							</div>
						</template>
						<div v-if="retry_time > 0" class="system">
							Reconnecting in {{ retry_time }}
						</div>
					</div>

					<transition-group name="roster" tag="div" class="roster">
						<div
							v-for="o in occupants"
							:class="['occupant', o==username?'self':'']"
							:key="o"
							:style="roster_colors[o]"
							>{{ o }}</div>
					</transition-group>
				</div>

				<div
					id="chat-box"
					:class="dragging?'dragging':''"
					@dragover="dragImage"
					@dragleave="dragging = false"
					@drop="dropImage">
					<form @submit.prevent="sendChat()">
						<div v-if="chatimg" class="preview">
							<div @click="chatimg = null" class="close">&times;</div>
							<img :src="chatimg_data">
						</div>
						<div class="expandingText">
							<pre><span>{{ chatbox }}</span><br></pre>
							<textarea
								placeholder="Say something!"
								v-model="chatbox"
								@keydown.enter.stop
								@keyup.enter.exact="sendChat()"></textarea>
						</div>
						<button type="submit">Send</button>
					</form>
				</div>
			</template>
			{% endverbatim nabu %}
		</div>
		<script src="{% static 'nabu/nabu.js' %}"></script>
		<script src="{% static 'nabu/parser.js' %}"></script>
	</body>
</html>

chat/templates/chat/pidgin.html
{% load static from staticfiles %}
{% load chat_extras %}
<p>
<a href="https://pidgin.im/" target="_blank">Pidgin</a> is our recommended chat
client for Windows and Linux users.
</p>

<h3>Setting up Pidgin</h3>
<p>
Once you have <a href="https://pidgin.im/download/" target="_blank">downloaded</a>
and installed Pidgin, add a new account by opening the Accounts menu and
selecting Manage Accounts, and then click the "Add..." button.
</p>
<div class="pull-right">
	<img src="{% static 'chat/img/pidgin_setup.png' %}" alt="Setup Pidgin" class="img-responsive" />
</div>
<p>
To configure your account, set your options as so:
</p>
<ol>
	<li>Protocol: {% jabber_proto %}</li>
	<li>Username: <span class="text-danger">{{ user.jid_node|default:"<em>Your username</em>" }}</span></li>
	<li>Domain: {% jabber_domain %}</li>
	<li>Resource: <em class="text-danger">Optionally identify this location to yourself.</em></li>
	<li>Password: <em class="text-danger">The <a class="text-danger" href="{% url 'auth:apppasswords' %}">App Password</a> you generated.</em></li>
</ol>
<p>
Under User Options, give yourself a Local alias; this only shows up to you, and
identifies your own messages. I like to set it to "Me".
</p>
<p>
Now click the Add button to finish and connect to the server.
</p>
{% include 'chat/annika-intro.html' %}