api/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from .views import StatusView


app_name = 'api'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^status$', StatusView.as_view(), name='status'),
]

fbxnano/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fbxnano.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^events$', TemplateView.as_view(template_name='events.html'), name='events'),
    url(r'^links$', TemplateView.as_view(template_name='links.html'), name='links'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^alerts/', include('alerts.urls', namespace='alerts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^auth/', include('prosodyauth.urls', namespace='auth')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^policies/', include('policies.urls', namespace='policies')),
)

forum/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from . import views

app_name = 'forum'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', views.IndexView.as_view(), name='index'),
    url('^search$', views.SearchView.as_view(), name='search'),
    url('^preview$', views.PreviewView.as_view(), name='preview'),

    url('^(?P<slug>[-\w]+)/$', views.BoardView.as_view(), name='board'),
    url('^(?P<slug>[-\w]+)/page-(?P<page>[0-9]+)$', views.BoardView.as_view(), name='board'),
    url('^(?P<board>[-\w]+)/post-(?P<pk>[0-9]+)$', views.PostView.as_view(), name='post'),

    url('^(?P<board>[-\w]+)/new$', views.TopicCreateView.as_view(), name='new-topic'),
    url('^(?P<board>[-\w]+)/post-(?P<post>[0-9]+)/reply$', views.ReplyCreateView.as_view(), name='new-reply'),
]

xmpp_dev/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xmpp_dev.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^auth/', include('prosodyauth.urls')),
)

forum/models.py
from django.conf import settings
from django.db import models,transaction
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe


from .markdown import MarkdownText


class MarkdownField(models.TextField):
    def from_db_value(self, value, expression, connection, context):
        return MarkdownText(value)

    def to_python(self, value):
        return MarkdownText(value)

    def get_prep_value(self, value):
        if value is None:
            return None
        return str(value)

    def get_internal_type(self):
        return 'TextField'


class BoardCategory(models.Model):
    title = models.CharField(max_length=25)

    def __str__(self):
        return self.title


class Board(models.Model):
    category = models.ForeignKey(
            BoardCategory,
            on_delete=models.PROTECT,
            related_name='boards',
            )
    title = models.CharField(max_length=25)
    slug = models.SlugField(blank=True, max_length=25)
    description = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        if not self.id and not self.slug:
            self.slug = slugify(self.title)

        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('forum:board', args=(self.slug,))

    @property
    def css(self):
        return 'label label-primary'

    def __str__(self):
        return self.title

    class Meta(object):
        ordering = ('slug',)


class Post(models.Model):
    user = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE,
            )
    op = models.ForeignKey(
            'self',
            null=True, default=None,
            on_delete=models.PROTECT,
            related_name='posts',
            )
    board = models.ForeignKey(
            Board,
            on_delete=models.PROTECT,
            related_name='posts',
            )
    subject = models.CharField(max_length=128)
    body = MarkdownField(help_text='<a data-toggle="modal" data-target="#MarkdownHelp"><span class="octicon octicon-markdown"></span> Markdown</a> will be used to format your post.', blank=True)
    left = models.PositiveIntegerField(default=0)
    right = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)
    readers = models.ManyToManyField(
            settings.AUTH_USER_MODEL,
            related_name='read_posts',
            )

    reply_to = None

    @property
    def reply_count(self):
        return int((self.right - self.left - 1) / 2)

    @property
    def ancestors(self):
        ancestors = [self.board]
        for post in Post.objects.filter(op_id=self.op_id).filter(left__lt=self.left).filter(right__gt=self.right).order_by('left'):
            ancestors.append(post)

        return ancestors

    @property
    def is_op(self):
        return self.id == self.op_id

    @property
    def css(self):
        if self.is_op:
            return 'label label-success'
        else:
            return 'label label-info'

    @property
    def nt(self):
        if len(self.body.markdown) == 0:
            return mark_safe('<span title="No Text" class="post-nt">(nt)</span>')
        return ''

    def get_absolute_url(self):
        return reverse('forum:post', args=(self.board.slug, self.pk))

    def __str__(self):
        return self.subject

    def save(self, *args, **kwargs):
        if self.reply_to:
            with transaction.atomic():
                # We need to lock the topic tree, to prevent race conditions
                if Post.objects.filter(op_id=self.reply_to.op_id).select_for_update():
                    pass

                # Make sure nobody else has updated this in the meantime
                self.reply_to.refresh_from_db()
                # Make room for our post
                Post.objects.filter(op_id=self.reply_to.op_id).filter(left__gt = self.reply_to.left).update(left = models.F('left') + 2)
                Post.objects.filter(op_id=self.reply_to.op_id).filter(right__gt = self.reply_to.left).update(right = models.F('right') + 2)

                # Now fit ourselves right into place
                self.left = self.reply_to.left + 1
                self.right = self.left + 1
                # Let's just make sure we have the topic set right
                self.op_id = self.reply_to.op_id
                self.board_id = self.reply_to.board_id

                return super().save()

        if self.right <= self.left:
            self.right = self.left + 1
        super().save(*args, **kwargs)

        if not self.op_id and self.id:
            self.op_id = self.id
            super().save(*args, **kwargs)

    class Meta(object):
        ordering = ('left',)

forum/forms.py
from django.forms import ModelForm,Textarea,TextInput


from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('subject','body')
        widgets = {
                'subject': TextInput(attrs={'autofocus':'autofocus'}),
                'body': Textarea(
                    attrs={
                        'data-provide':'markdown',
                        'data-hidden-buttons':'cmdHeading',
                        'data-iconlibrary':'octicons',
                        'data-resize': 'vertical',
                        }),
                }

forum/views.py
import shlex


from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q,F,Count,Case,When,Sum,IntegerField,Min
from django.http import HttpResponse
from django.views.generic import DetailView,ListView,View
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404,render


from forum.forms import PostForm
from forum.markdown import MarkdownText
from forum.models import Board,Post


# Create your views here.

class ForumViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['board_list'] = Board.objects.select_related('category').order_by('category__title', 'slug')

        return context


class IndexView(ForumViewMixin, ListView):
    queryset = Post.objects.select_related('op', 'board', 'user').order_by('-date')[:10]
    context_object_name = 'posts'

    def get_queryset(self):
        qs = super().get_queryset()

        if self.request.user.is_authenticated:
            # @see PostView.get_context_data()
            qs = qs.annotate(
                    unread=Min(
                        Case(
                            When(readers=self.request.user, then=0),
                            default=1,
                            output_field=IntegerField(),
                            )
                        )
                    )

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Most Recent Posts'
        return context


class BoardView(ForumViewMixin, DetailView):
    model = Board
    context_object_name = 'board'
    topics_per_page = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        self.page = self._get_page()

        qs = self.object.posts.filter(op_id=F('id')).annotate(post_count=Count('posts', distinct=True)).order_by('-date')
        qs = qs.annotate(author=F('user__username'))
        topics = self._paginate_queryset(qs)

        if self.request.user.is_authenticated:
            # This "Sum" annotation, thanks to the Case we're using within it,
            # has the same effect as a subquery using Count to determine how
            # many posts within each topic the current user has actually read.
            # As a convenience for our templates, we then use this and the post
            # count (annotated above whether user is auth'd or not) to calculate
            # the number of posts the user has not yet read in each.
            topics = topics.annotate(
                    read_count=Sum(
                        Case(
                            When(posts__readers=self.request.user, then=1),
                            default=0,
                            output_field=IntegerField(),
                            )
                        )).annotate(
                    unread_count=F('post_count')-F('read_count'),
                    )
        context['topics'] = topics

        # Don't forget that internally page is 0-indexed, but it's 1-indexed out front
        if self.page > 0:
            context['prev_page'] = self.page
        if self.page < self._get_last_page():
            context['next_page'] = self.page + 2

        return context

    def _get_page(self):
        page = self.kwargs.get('page') or 1
        return int(page) - 1

    def _paginate_queryset(self, qs):
        start = self.page * self.topics_per_page
        stop = start + self.topics_per_page

        self.total_topics = qs.count()

        return qs[start:stop]

    def _get_last_page(self):
        return int(self.total_topics / self.topics_per_page)


class PostView(ForumViewMixin, DetailView):
    model = Post
    context_object_name = 'post'

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)

        if self.request.user.is_authenticated:
            obj.readers.add(self.request.user)

        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['form'] = PostForm()

        thread = self.object.op.posts.annotate(author=F('user__username'))
        if self.request.user.is_authenticated:
            # This looks fugly, but we need to annotate our Posts with their
            # "read" state for the current user, but without duplicating them
            # as a straight JOIN would. Therefore we have to use an aggregate
            # function -- in this case, Min -- to get the appropriate GROUP BY
            # clause in the query Django generates. By using Min and a Case
            # function that assigns 0 to the user and 1 to anything else, we
            # end up with a simple boolean-ish "unread" flag on each Post.
            thread = thread.annotate(
                    unread=Min(
                        Case(
                            When(readers=self.request.user, then=0),
                            default=1,
                            output_field=IntegerField(),
                            )
                        )
                    )
        context['authenticated'] = str(self.request.user.is_authenticated)
        context['thread'] = thread

        return context

    def get_queryset(self):
        self.board = get_object_or_404(Board, slug=self.kwargs['board'])
        return Post.objects.filter(board=self.board)


class SearchView(ForumViewMixin, ListView):
    model = Post
    context_object_name = 'posts'

    def _split_query_string(self, query_string):
        try:
            return shlex.split(query_string)
        except ValueError:
            # Users may not be careful about always closing quotes
            return query_string.split(' ')

    def _build_filter(self, search_terms):
        for term in search_terms:
            yield Q(body__icontains=term) | Q(subject__icontains=term)

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q', None)

        if not q:
            # No query, no results
            qs = qs.filter(subject=None)
        else:
            split_q = self._split_query_string(q)

            qs = qs.filter(*self._build_filter(split_q))

        return qs.order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Search Results'
        context['search_query'] = self.request.GET.get('q', '')
        return context


class ForumPostMixin(LoginRequiredMixin, ForumViewMixin):
    form_class = PostForm
    template_name = 'forum/post_form.html'

    def dispatch(self, *args, **kwargs):
        self.board = get_object_or_404(Board, slug=self.kwargs['board'])
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['board'] = self.board

        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.board = self.board
        return super().form_valid(form)


class TopicCreateView(ForumPostMixin, CreateView):
    form_class = PostForm
    template_name = 'forum/post_form.html'

    def form_valid(self, form):
        return super().form_valid(form)


class ReplyCreateView(ForumPostMixin, CreateView):
    form_class = PostForm
    template_name = 'forum/post_form.html'

    def dispatch(self, *args, **kwargs):
        self.reply_to = get_object_or_404(Post, pk=self.kwargs['post'])
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['post'] = self.reply_to

        return context

    def form_valid(self, form):
        form.instance.reply_to = self.reply_to
        return super().form_valid(form)


class PreviewView(View):
    def post(self, request):
        md = request.POST.get('body', '')

        return HttpResponse(MarkdownText(md).html)

forum/templates/forum/base.html
{% extends 'forum/base_skeleton.html' %}
{% load forum_extras %}


{% block content %}
<nav class="navbar navbar-default navbar-subnav">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#forum-navbar-collapse" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'forum:index' %}">Forum</a>
		</div>

		<div class="collapse navbar-collapse" id="forum-navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="dropdown board-dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
						aria-expanded="false">Boards <span class="caret"></span></a>
					<ul class="dropdown-menu">
						{% include 'forum/board_block.html' with boards=board_list only %}
					</ul>
				</li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				{#<li><a href="#">My Posts</a></li>#}
				{#<li><a href="#">New Replies <span class="badge">12</span></a></li>#}
				{% else %}
				<li class="navbar-text">Login to join the conversation</li>
				{% endif %}
				{% block context_navs %}{% endblock %}
				<li>
					<form action="{% url 'forum:search' %}" method="get" class="navbar-form" id="post-search" tabindex="-1">
						<div class="form-group">
							<input type="text" name="q" placeholder="Search" value="{{ search_query }}">
						</div>
					</form>
				</li>
			</ul>
		</div>
	</div>
</nav>

{% if post %}
<div class="post-breadcrumbs">
	<ol class="breadcrumb">
		{% for ancestor in post.ancestors %}
		<li><a href="{{ ancestor.get_absolute_url }}" class="{{ ancestor.css }}">{{ ancestor.subject }}{{ ancestor.title }}</a></li>
		{% endfor %}
		<li class="active"><span class="label label-default">{{ post.subject }}</span></li>
	</ol>
</div>
{% endif %}

<div class="forum-wrapper clearfix{% if post %} post-wrapper{% endif %}">
	<h2>{% block forum_title %}{% endblock forum_title %}</h2>
	{% block forum_content %}{% endblock forum_content %}
</div>

{% if post %}{% post_tree %}{% endif %}
{% endblock %}

forum/templates/forum/base_skeleton.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/forum.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-markdown.min.css' %}">
{% endblock extrahead %}

{% block header_frame %}{% endblock %}
{% block title %}{% block forum_title %}{% endblock forum_title %} — AKWriters Forum{% endblock title %}

{% block extrascripts %}
<script src="{% static 'js/forum.js' %}"></script>
<script src="{% static 'js/jquery.hotkeys.js' %}"></script>
<script src="{% static 'js/bootstrap-markdown.js' %}"></script>
{% endblock extrascripts %}

forum/templates/forum/board_block.html
{% for board in boards %}
{% ifchanged board.category %}
{% if not forloop.first %}
	</ul>
</li>
{% endif %}
<li class="dropdown-submenu">
	<a role="button" class="dropdown-toggle">{{ board.category.title }} <span class="caret"></span></a>
	<ul class="dropdown-menu">
		{% endifchanged %}
		<li>
			<a href="{% url 'forum:board' slug=board.slug %}">{{ board.title }}</a>
		</li>
		{% endfor %}
	</ul>
</li>

forum/templates/forum/board_detail.html
{% extends 'forum/base.html' %}
{% load frontend_extras %}

{% block forum_title %}
{{ board.title }}
{% endblock %}

{% block context_navs %}
{% if user.is_authenticated %}
<li><a href="{% url 'forum:new-topic' board=board.slug %}">{% octicon 'diff-added' %} New Thread</a></li>
{% endif %}
{% endblock %}

{% block forum_content %}
<div class="board-description">{{ board.description }}</div>
<div class="post-list">
	{% for topic in topics %}
	<div>
		<a href="{% url 'forum:post' board=board.slug pk=topic.pk %}" class="{{ topic.css }}">{{ topic.subject }}</a>{{ topic.nt }}
		Started {{ topic.date|date:'P N j Y' }} by <span class="author">{{ topic.author }}</span>
		({{ topic.post_count }} post{{ topic.post_count|pluralize }})
		{% if topic.unread_count %}<span class="post-unread">({{ topic.unread_count }} new!)</span>{% endif %}
	</div>
	{% empty %}
	<div class="warning-text text-center">Looks like there's nothing here yet! Ready to start the conversation?</div>
	{% endfor %}

	<nav class="clearfix">
		<ul class="pager">
			{% if prev_page %}
			<li class="previous"><a href="{% url 'forum:board' slug=board.slug page=prev_page %}"><span class="aria-hidden">&larr;</span> Previous</a></li>
			{% else %}
			<li class="previous disabled"><span><span class="aria-hidden">&larr;</span> Previous</span></li>
			{% endif %}

			{% if next_page %}
			<li class="next"><a href="{% url 'forum:board' slug=board.slug page=next_page %}">Next <span class="aria-hidden">&rarr;</span></a></li>
			{% else %}
			<li class="next disabled"><span>Next <span class="aria-hidden">&rarr;</span></span></li>
			{% endif %}
		</ul>
	</nav>
</div>
{% endblock %}

forum/templates/forum/board_list.html
{% extends 'base.html' %}
{% load frontend_extras %}
{% load static from staticfiles %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/forum.css' %}">
{% endblock extrahead %}

{% block title %}
AKWriters Forum
{% endblock title %}

{% block header %}
AKWriters Forum
{% endblock header %}

{% block content %}
{% include 'forum/board_block.html' with boards=board_list only %}
{% endblock %}

forum/templates/forum/markdown_help.html
<div class="modal fade" id="MarkdownHelp" tabindex="-1" role="dialog" aria-labelledby="MarkdownHelpLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="MarkdownHelpLabel">Formatting Help</h4>
			</div>
			<div class="modal-body">
				We use a slightly-customized version of Markdown to format your
				posts. See below for the basics, or check the
				<a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">official Markdown page</a>
				for more that you can do.

				<table class="table">
					<thead>
						<tr>
							<th>You type...</th>
							<th>...you see</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>*italics*</td>
							<td><em>italics</em></td>
						</tr>
						<tr>
							<td>**bold**</td>
							<td><strong>bold</strong></td>
						</tr>
						<tr>
							<td>[AKWriters!](https://akwriters.org)</td>
							<td><a href="https://akwriters.org">AKWriters!</a></td>
						</tr>
						<tr>
							<td>
								* item 1<br>
								* item 2<br>
								* item 3<br>
							</td>
							<td>
								<ul>
									<li>item 1</li>
									<li>item 2</li>
									<li>item 3</li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>&gt; quoted text</td>
							<td><blockquote>quoted text</blockquote></td>
						</tr>
						<tr>
							<td>super^script</td>
							<td>super<sup>script</sup></td>
						</tr>
						<tr>
							<td>~~strikethrough~~</td>
							<td><del>strikethrough</del></td>
						</tr>
						<tr>
							<td>==highlight==</td>
							<td><mark>highlight</mark></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

forum/templates/forum/post_detail.html
{% extends 'forum/base.html' %}
{% load frontend_extras %}

{% block forum_title %}{{ post.subject }}{% endblock %}

{% block context_navs %}
{% if user.is_authenticated %}
<li><a href="{% url 'forum:new-reply' board=post.board.slug post=post.pk %}" id="toolbar-reply">{% octicon 'reply' %} Reply</a></li>
{% endif %}
{% endblock %}

{% block forum_content %}
<div class="post-meta">
	Posted by <span class="author">{{ post.user.username }}</span> at {{ post.date|date:'P l, F jS, Y' }}
</div>
{% if not post.nt %}
<div class="post">
	{{ post.body.html }}
	<button class="btn btn-default btn-xs" id="show-source">Show Source</button>
</div>
{# We need to be careful about newlines here because we preserve them #}
<div class="post-source">{{ post.body.markdown }}
	<button class="btn btn-default btn-xs" id="hide-source">Hide Source</button>
</div>
{% else %}
<div class="text-info text-center">
	<em>No text was supplied with this post.</em>
</div>
{% endif %}

<div class="post-reply">
	{% if user.is_authenticated %}
	<button class="btn btn-sm btn-success" id="reply">{% octicon 'reply' %} Reply</button>
	<form action="{% url 'forum:new-reply' board=post.board.slug post=post.pk %}" method="POST" id="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="text-right">
			<button class="btn btn-default" id="reply-cancel">Cancel</button>
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
	</form>
	{% else %}
	{#Stubbing this out for when post-login redirection is implemented#}
	{#<a class="btn btn-sm btn-success" href="{% url 'forum:new-reply' board=post.board.slug post=post.pk %}">{% octicon 'reply' %} Reply</a>#}
	{% endif %}
</div>

{% include 'forum/markdown_help.html' %}
{% endblock %}

forum/templates/forum/post_form.html
{% extends 'forum/base.html' %}

{% block forum_title %}
{% if post %}
Replying to {{ post.subject }}
{% else %}
New thread on {{ board.title }}
{% endif %}
{% endblock %}

{% block forum_content %}
<form action="" method="POST" id="post-form">
	{% csrf_token %}
	{{ form.as_p }}
	<div class="text-right">
		<a href="{% if post %}{% url 'forum:post' board=board.slug pk=post.pk %}{% else %}{% url 'forum:board' slug=board.slug %}{% endif %}" class="btn btn-default">Cancel</a>
		<button type="submit" class="btn btn-success">Submit</button>
	</div>
</form>

{% include 'forum/markdown_help.html' %}
{% endblock %}

forum/templates/forum/post_list.html
{% extends 'forum/base.html' %}

{% block forum_title %}{{ title }}{% endblock %}

{% block forum_content %}
<div class="post-list">
	{% for post in posts %}
	<div>
		<a href="{% url 'forum:board' slug=post.board.slug %}" class="{{ post.board.css }}">{{ post.board.title }}</a>
		<a href="{% url 'forum:post' board=post.board.slug pk=post.pk %}" class="{{ post.css }}">{{ post.subject }}</a>{{ post.nt }}
		{% if post.unread %}<span class="post-unread">New!</span>{% endif %}
		by <span class="author">{{ post.user.username }}</span>
		({{ post.date|date:'P N j' }})
	</div>
	{% empty %}
	<div class="text-center">
		<em>Sorry, no posts found.</em>
	</div>
	{% endfor %}
</div>
{% endblock %}

forum/templates/forum/post_tree.html
{% load frontend_extras %}
{% load forum_extras %}
<div class="post-tree">
	{% for post in thread %}
	{% for i in post|parents:parents %}
	</div>
	{% endfor %}
	<div>
	{% if post == current_post %}
	<span class="label label-default">{% octicon 'arrow-right' %}{{ post.subject }}</span>{{ post.nt }}
	{% else %}
	<a href="{{ post.get_absolute_url }}" class="{{ post.css }}">{{ post.subject }}</a>{{ post.nt }}
	{% endif %}
	{% if post.unread %}<span class="post-unread">New!</span>{% endif %}
	- <span class="author">{{ post.author }}</span> {{ post.date|date:"P M j 'y"}}
	<br>
	{% endfor %}
	{% close_tree %}
</div>