account/urls.py
from django.conf.urls import include, url


from .views import AccountSettingsView


urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^settings', AccountSettingsView.as_view(), name='settings'),
]

api/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from .views import StatusView


app_name = 'api'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^status$', StatusView.as_view(), name='status'),
]

chat/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView


from . import views

app_name = 'chat'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    path('', TemplateView.as_view(template_name='chat/index.html'), name='index'),
    path('nabu', login_required(views.NabuView.as_view()), name='nabu'),
    #url(r'^candy$', login_required(views.CandyView.as_view()), name='candy'),
]

contact/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'contact'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.contact, name='contact'),
]

events/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from . import views

app_name = 'events'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', views.EventsView.as_view(), name='index'),
    url('^(?P<year>[\d]{4})(?P<month>[\d]{2})$', views.EventsView.as_view(), name='index'),
    url('^calendars.css$', views.CalendarCssView.as_view(), name='calendars_css'),
]

favicon/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'favicon'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^manifest.json$', views.manifest, name='manifest'),
    url(r'^browserconfig.xml$', views.browserconfig, name='browserconfig'),
]

fbxnano/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fbxnano.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^events$', TemplateView.as_view(template_name='events.html'), name='events'),
    url(r'^links$', TemplateView.as_view(template_name='links.html'), name='links'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^alerts/', include('alerts.urls', namespace='alerts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^auth/', include('prosodyauth.urls', namespace='auth')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^policies/', include('policies.urls', namespace='policies')),
)

forum/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from . import views

app_name = 'forum'
urlpatterns = [
    # Examples:
    # url(r'^$', 'akwriters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^$', views.IndexView.as_view(), name='index'),
    url('^search$', views.SearchView.as_view(), name='search'),
    url('^preview$', views.PreviewView.as_view(), name='preview'),

    url('^(?P<slug>[-\w]+)/$', views.BoardView.as_view(), name='board'),
    url('^(?P<slug>[-\w]+)/page-(?P<page>[0-9]+)$', views.BoardView.as_view(), name='board'),
    url('^(?P<board>[-\w]+)/post-(?P<pk>[0-9]+)$', views.PostView.as_view(), name='post'),

    url('^(?P<board>[-\w]+)/new$', views.TopicCreateView.as_view(), name='new-topic'),
    url('^(?P<board>[-\w]+)/post-(?P<post>[0-9]+)/reply$', views.ReplyCreateView.as_view(), name='new-reply'),
]

events/models.py
import datetime
import json
from urllib import request,parse


from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.
class Calendar(models.Model):
    name = models.CharField(max_length=30, unique=True)
    remote_id = models.CharField(max_length=60)
    style_bgcolor = models.CharField(max_length=20, default='white')
    style_textcolor = models.CharField(max_length=20, default='black')

    @property
    def css_class(self):
        return 'event-' + slugify(self.name)

    def get_events(self, month):
        cache, created = MonthCache.objects.get_or_create(calendar=self, month=month)
        return cache.data

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name',]


class MonthCache(models.Model):
    calendar = models.ForeignKey(Calendar, on_delete=models.CASCADE)
    month = models.DateField()
    data_cache = models.TextField()
    data_cached_on = models.DateTimeField()

    _base_url = 'https://www.googleapis.com/calendar/v3/calendars/{calendar}/events?singleEvents=true&timeMin={time_min}&timeMax={time_max}&key={api_key}'
    _cache_expires = datetime.timedelta(minutes=settings.GAPI_CACHE_EXPIRES)

    @property
    def url(self):
        # Normalize self.month to the first of the month
        self.month = datetime.date(self.month.year, self.month.month, 1)

        # Extend beyond the month to ensure we have everything we want to display
        time_min = self.month - datetime.timedelta(days=7)
        time_max = self.month + datetime.timedelta(days=37)

        # Need ISO format including time
        time_min = time_min.isoformat() + 'T00:00:00Z'
        time_max = time_max.isoformat() + 'T00:00:00Z'

        return self._base_url.format(
                calendar=parse.quote(self.calendar.remote_id),
                time_min=parse.quote(time_min),
                time_max=parse.quote(time_max),
                api_key=parse.quote(settings.GCAL_API_KEY),
                )

    @property
    def is_cache_stale(self):
        if self.data_cache is None:
            return True
        elif self.data_cached_on is None:
            return True
        elif self.data_cached_on + self._cache_expires < timezone.now():
            return True

        return False

    @property
    def data(self):
        return self._get_data(auto_save=True)

    def _get_data(self, auto_save):
        url = self.url

        if self.is_cache_stale:
            self.data_cache = request.urlopen(url).read().decode('utf8')
            self.data_cached_on = timezone.now()

            if auto_save:
                self.save()

        return json.loads(self.data_cache)

    def __str__(self):
        if self.is_cache_stale:
            return "{calendar} ({month}) [STALE]".format(
                    calendar=self.calendar,
                    month=self.month.isoformat()[:7]
                    )
        else:
            return "{calendar} ({month})".format(
                    calendar=self.calendar,
                    month=self.month.isoformat()[:7]
                    )

    def save(self, *args, **kwargs):
        self._get_data(auto_save=False)
        super().save(*args, **kwargs)

events/views.py
import datetime
import calendar


from django.shortcuts import render
from django.views.generic import TemplateView,RedirectView
from django.utils import dateparse,timezone


from .models import Calendar,MonthCache
from . import utils


# Create your views here.
class CalendarCssView(TemplateView):
    template_name = 'events/calendars.css'
    content_type = 'text/css'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['calendars'] = Calendar.objects.all()

        return context


class EventsView(TemplateView):
    template_name = 'events/index.html'

    year = None
    month = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        today = timezone.localtime(timezone.now()).date()
        try:
            self.year = int(self.kwargs['year'])
            self.month = int(self.kwargs['month'])
        except KeyError:
            self.year = today.year
            self.month = today.month

        current_month = datetime.date(self.year, self.month, 1)
        dates = calendar.Calendar(6).monthdatescalendar(current_month.year, current_month.month)

        events = {}
        gcals = Calendar.objects.all()
        for gcal in gcals:
            gdata = gcal.get_events(current_month)

            for event in gdata['items']:
                event['css_class'] = gcal.css_class
                try:
                    startdate = dateparse.parse_datetime(event['start']['dateTime'])
                    enddate = dateparse.parse_datetime(event['end']['dateTime'])

                    event['start_time'] = startdate.time()
                    event['end_time'] = enddate.time()

                    startdate = startdate.date()
                    enddate = enddate.date()
                except KeyError:
                    startdate = dateparse.parse_date(event['start']['date'])
                    enddate = dateparse.parse_date(event['end']['date'])

                event['start_date'] = startdate
                event['end_date'] = enddate

                try:
                    events[startdate.isoformat()].append(event)
                except KeyError:
                    events[startdate.isoformat()] = [event,]

        cal = []
        for week in dates:
            cal.append([])
            for date in week:
                isodate = date.isoformat()
                date_events = events.get(isodate, [])
                date_events.sort(key=utils.event_key)

                cal[-1].append({
                    'date': date,
                    'events': date_events,
                    })

        context['calendar'] = cal
        context['gcals'] = gcals
        context['current_month'] = current_month
        context['last_month'] = current_month - datetime.timedelta(days=1)
        context['next_month'] = current_month + datetime.timedelta(days=32)
        context['today'] = today

        return context

favicon/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.staticfiles.templatetags.staticfiles import static

# Create your views here.

_icon_sizes = (36, 48, 72, 96, 144, 192)
def manifest(request):
    manifest_data = {}
    manifest_data['name'] = 'Alaska Writers'

    icon_data = []

    for size in _icon_sizes:
        """
        "src": "\/static\/favicons\/android-chrome-36x36.png",
        "sizes": "36x36",
        "type": "image\/png",
        "density": "0.75"
        """
        size = str(size)

        icon = {}

        icon_file = 'android-chrome-{size}x{size}.png'.format(size=size)
        icon['src'] = static('favicon/{file}'.format(file=icon_file))

        icon['sizes'] = '{size}x{size}'.format(size=size)
        icon['type'] = 'image/png'
        icon['density'] = '0.75'

        icon_data.append(icon)

    manifest_data['icons'] = icon_data

    return JsonResponse(manifest_data)

def browserconfig(request):
    return render(request, 'favicon/browserconfig.xml', content_type='application/xml')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{# The following meta tags *must* come before all other head content #}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{# The preceding meta tags *must* come before all other head content #}

{% load static from staticfiles %}
{% load frontend_extras %}

<title>{% block title %}AKWriters{% endblock %}</title>

<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" href="{% static 'octicons/octicons.min.css' %}">
<link rel="stylesheet" href="{% static 'css/site.css' %}">
{% block extrahead %}{% endblock %}

{% include 'favicon/head.html' %}

</head>

<body>

{% include 'navbar.html' %}

{% if messages %}
<div id="alert-container" class="col-xs-6 col-sm-4 col-md-3">
	{% for message in messages %}
	<div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
		{% if message.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}
			{% octicon 'bug' 'Debug:' %}
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
			{% octicon 'info' %}
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
			{% octicon 'thumbsup' 'Success:' %}
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
			{% octicon 'stop' 'Warning:' %}
		{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
			{% octicon 'flame' 'ERROR:' %}
		{% else %}
			{% octicon 'question' %}
		{% endif %}
		{{ message }}
		<button type="button" class="close" aria-label="Close">
			<span aria-hidden="true">{% octicon 'trashcan' %}</span>
		</button>
	</div>
	{% endfor %}
</div>
{% endif %}

<div class="container">
	<div id="site_content">
		<div class="row">
			{% block header_frame %}<h2>{% block header %}Welcome to AKWriters{% endblock header %}</h2>{% endblock header_frame %}
			{% block content %}{% endblock content %}
		</div>
	</div>
</div>

<footer>
	&copy; 2015-{% now 'Y' %} AKWriters. Site by Travis Veazey
	<a href="https://github.com/Kromey/akwriters" target="_blank">{% octicon 'octoface' %}</a>.
	Icons by <a href="https://octicons.github.com/" target="_blank">GitHub</a>.
	<br>
	Your use of this site constitutes acceptance
	of the
	<a href="{% url 'policies:terms_of_service' %}">Terms of Service</a>
	and
	<a href="{% url 'policies:privacy' %}">Privacy and Cookie Policy</a>.
</footer>

{# Bootstrap requires JQuery #}
<script src="{% static 'jquery/jquery-2.1.4.min.js' %}"></script>
{# Bootstrap JS at bottom so that it doesn't block page loading #}
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/akwriters.js' %}"></script>
{% block extrascripts %}{% endblock %}
</body>
</html>

templates/events.html
{% extends 'base.html' %}

{% block title %}
Alaska Writers Events
{% endblock title %}

{% block header %}
Alaska Writers Events
{% endblock header %}

{% block content %}
{# Note: May need to alter CSP to embed an iframe here #}
<div class="calendar">
	<div class="calendar-week">
		<div class="calendar-day">
			<span class="day-label">1</span>
			<div class="event event-anc"><span class="label">Foobar bad beef baz bax barrister</span></div>
			<div class="event event-fbx"><span class="label">Foobar bad beef</span></div>
			<div class="event event-els"><span class="label">Foobar bad beef</span></div>
		</div>
		<div class="calendar-day"><span class="day-label">2</span></div>
		<div class="calendar-day"><span class="day-label">3</span></div>
		<div class="calendar-day"><span class="day-label">4</span></div>
		<div class="calendar-day"><span class="day-label">5</span></div>
		<div class="calendar-day"><span class="day-label">6</span></div>
		<div class="calendar-day"><span class="day-label">7</span></div>
	</div>
	<div class="calendar-week">
		<div class="calendar-day">
			<span class="day-label">1</span>
			<div class="event event-anc"><span class="label">Foobar bad beef baz bax barrister</span></div>
			<div class="event event-fbx"><span class="label">Foobar bad beef</span></div>
			<div class="event event-els"><span class="label">Foobar bad beef</span></div>
		</div>
		<div class="calendar-day"><span class="day-label">2</span></div>
		<div class="calendar-day"><span class="day-label">3</span></div>
		<div class="calendar-day"><span class="day-label">4</span></div>
		<div class="calendar-day"><span class="day-label">5</span></div>
		<div class="calendar-day"><span class="day-label">6</span></div>
		<div class="calendar-day"><span class="day-label">7</span></div>
	</div>
	<div class="calendar-week">
		<div class="calendar-day">
			<span class="day-label">1</span>
			<div class="event event-anc"><span class="label">Foobar bad beef baz bax barrister</span></div>
			<div class="event event-fbx"><span class="label">Foobar bad beef</span></div>
			<div class="event event-els"><span class="label">Foobar bad beef</span></div>
		</div>
		<div class="calendar-day"><span class="day-label">2</span></div>
		<div class="calendar-day"><span class="day-label">3</span></div>
		<div class="calendar-day"><span class="day-label">4</span></div>
		<div class="calendar-day"><span class="day-label">5</span></div>
		<div class="calendar-day"><span class="day-label">6</span></div>
		<div class="calendar-day"><span class="day-label">7</span></div>
	</div>
	<div class="calendar-week">
		<div class="calendar-day">
			<span class="day-label">1</span>
			<div class="event event-anc"><span class="label">Foobar bad beef baz bax barrister</span></div>
			<div class="event event-fbx"><span class="label">Foobar bad beef</span></div>
			<div class="event event-els"><span class="label">Foobar bad beef</span></div>
		</div>
		<div class="calendar-day"><span class="day-label">2</span></div>
		<div class="calendar-day"><span class="day-label">3</span></div>
		<div class="calendar-day"><span class="day-label">4</span></div>
		<div class="calendar-day"><span class="day-label">5</span></div>
		<div class="calendar-day"><span class="day-label">6</span></div>
		<div class="calendar-day"><span class="day-label">7</span></div>
	</div>
	<div class="calendar-week">
		<div class="calendar-day">
			<span class="day-label">1</span>
			<div class="event event-anc"><span class="label">Foobar bad beef baz bax barrister</span></div>
			<div class="event event-fbx"><span class="label">Foobar bad beef</span></div>
			<div class="event event-els"><span class="label">Foobar bad beef</span></div>
		</div>
		<div class="calendar-day"><span class="day-label">2</span></div>
		<div class="calendar-day"><span class="day-label">3</span></div>
		<div class="calendar-day"><span class="day-label">4</span></div>
		<div class="calendar-day"><span class="day-label">5</span></div>
		<div class="calendar-day"><span class="day-label">6</span></div>
		<div class="calendar-day"><span class="day-label">7</span></div>
	</div>
</div>
{% endblock content %}

templates/favicons.html
<link rel="apple-touch-icon" sizes="57x57" href="/static/favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/static/favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/static/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/static/favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/static/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/static/favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/static/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/static/favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/static/favicons/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/static/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/static/favicons/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/static/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/static/favicons/manifest.json">
<link rel="mask-icon" href="/static/favicons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/favicons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Alaska Writers">
<meta name="application-name" content="Alaska Writers">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/static/favicons/mstile-144x144.png">
<meta name="msapplication-config" content="/static/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

templates/index.html
{% extends 'base.html' %}

{% block content %}
<p>
Welcome!
</p>
<p>
AKWriters is a writers' community that owes its origins to <a href="http://nanowrimo.org/" target="_blank">National Novel Writing Month</a> and to the Fairbanks region, but which has grown beyond both of those to become a year-round community for the entire state and beyond.
</p>
<p>
Be sure to check out our new <a href="{% url 'forum:index' %}">forums</a>, and don't forget to take a look at our <a href="{% url 'resources' %}">book recommendations</a>. Then come join the conversation on our <a href="{% url 'chat:index' %}">chat server</a>!
</p>
{% endblock content %}

templates/links.html
{% load frontend_extras %}
<li><a href="http://nanowrimo.org/" target="_blank">{% octicon 'pencil' %} NaNoWriMo</a></li>

<li role="separator" class="divider"></li>
<li class="dropdown-header">Useful Articles</li>
<li><a href="http://www.writinghope.com/31-days-of-nano-prep/" target="_blank">31 Days Of Nano Prep</a></li>
<li><a href="https://kromey.us/2013/11/backing-up-your-stories-with-scrivener-and-dropbox-599.html" target="_blank">Backup Your Stories With Scrivener and Dropbox</a></li>

<li role="separator" class="divider"></li>
<li class="dropdown-header">Generators &amp; Ideas</li>
<li><a href="http://www.scifiideas.com/" target="_blank">SciFi Ideas</a></li>
<li><a href="http://www.seventhsanctum.com/" target="_blank">Seventh Sanctum</a></li>
<li><a href="http://writeordie.com/" target="_blank">Write or Die 2</a></li>
<li><a href="http://worldbuilding.stackexchange.com/" target="_blank">World Building Q&amp;A</a></li>
<li><a href="http://donjon.bin.sh/" target="_blank">donjon RPG Tools</a></li>

templates/navbar.html
{% load frontend_extras %}
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'index' %}">AKWriters</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
						aria-expanded="false">{% octicon 'organization' %} Community <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'chat:index' %}">{% octicon 'comment-discussion' %} Chat</a></li>
						<li><a href="{% url 'forum:index' %}">{% octicon 'book' %} Forum</a></li>
						{# <li><a href="/profiles">Profiles</a></li> #}
						<li><a href="{% url 'events:index' %}">{% octicon 'calendar' %} Events</a></li>
						<li><a href="{% url 'contact:contact' %}">{% octicon 'mail' %} Contact Us</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
						aria-expanded="false">{% octicon 'link' %} Links <span class="caret"></span></a>
					<ul class="dropdown-menu">
						{% include 'links.html' %}
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
						aria-expanded="false">{% octicon 'beaker' %} Resources <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'tools:story_list' %}">{% octicon 'repo-clone' %} Stories</a></li>
						<li><a href="{% url 'resources' %}">{% octicon 'bookmark' %} Recommended Books</a></li>
					</ul>
				</li>
				{% if user.is_authenticated %}
				<li>
					<button type="button" class="btn btn-info navbar-btn" data-popup-uri="{% url 'chat:nabu' %}">{% octicon 'comment-discussion' %} Join Chat</button>
				</li>
				{% endif %}
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
						aria-expanded="false">{% octicon 'person' %} {{ user.username }} <span class="caret"></span></a>
					<ul class="dropdown-menu">
						{% if user.is_superuser %}
						<li><a href="{% url 'admin:index' %}">{% octicon 'database' %} Admin</a></li>
						{#<li><a href="{% url 'events:purge' %}">{% octicon 'zap' %} Clear Event Cache</a></li>#}
						<li role="separator" class="divider"></li>
						{% endif %}
						{#<li><a href="{% url 'account:settings' %}">{% glyphicon 'cog' %} Account Settings</a></li>#}
						{#<li><a href="{% url 'auth:apppasswords' %}">{% octicon 'shield' %} App Passwords <span class="badge">{{ user.apppassword_set.count }}</span></a></li>#}
						<li><a href="{% url 'auth:logout' %}?next={{ request.path }}">{% octicon 'sign-out' %} Logout</a></li>
					</ul>
				</li>
				{% else %}
				<li><a href="{% url 'auth:login' %}?next={{ request.path }}">{% octicon 'sign-in' %} Login</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>

templates/panel-base.html
{# Base template for a generic Bootstrap panel with heading and body blocks #}
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">{% block paneltitle %}{% endblock %}</h3>
	</div>
	<div class="panel-body">
		{% block panelbody %}{% endblock %}
	</div>
</div>